version: '3.8'
services:
  fiveminutes:
    container_name: fiveminutes
    image: postgres:latest
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - fiveminutes-volume:/var/lib/postgresql/data
  
  seq:
    image: datalust/seq:latest
    ports:
      - 80:80
      - 5341:5341
    environment:
      - ACCEPT_EULA=Y

volumes:
  fiveminutes-volume: